--- 
artifacts: 
  files: 
    - '**/*'
  base-directory: 'build'
  discard-paths: no
phases: 
  build: 
    commands: 
      - "echo Build Phase"
      - "npm run build"
  install: 
    commands: 
      - "echo \"installing nodejs\""
      - "npm i npm@latest -g"
  post_build: 
    commands: 
      - "echo PostBuild Phase"
      - "cp appspec.yml build/appspec.yml"
  pre_build: 
    commands: 
      - "echo Pre_build Phase"
      - "npm install"
version: 0.1
