--- 
artifacts: 
  files: 
    - 'build/*'
phases: 
  build: 
    commands: 
      - "echo Build Phase"
      - "npm run build"
  install: 
    commands: 
      - "echo \"installing nodejs\""
      - "npm i npm@latest -g"
      - "pip install --upgrade pip"
      - "pip install --upgrade awscli"
  post_build: 
    commands: 
      - "echo PostBuild Phase"
  pre_build: 
    commands: 
      - "echo Pre_build Phase"
      - "npm install"
version: 0.1