version: 1

phases:
  install:
 
    commands:
      - echo "installing nodejs"
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install
  build:
    commands:
      - echo Build Phase

  post_build:
    commands:
      - echo PostBuild Phase