--- 
artifacts: 
  files:
     - '**/*'
  exclude-paths: 
     - 'node_modules'
     - '.git'
  secondary-artifacts:
    build-artifect:
      files:
        - '**/*'
      base-directory: 'build'
      discard-paths: no
      name: build-artifect
    appspec-artifact:
      files:
        - appspec.yml
      name: appspec-artifact
phases: 
  build: 
    commands: 
      - "echo Build Phase"
      - "npm run build"
  install: 
    commands: 
      - "echo \"installing nodejs\""
      - "npm i npm@latest -g"
  post_build: 
    commands: 
      - "echo PostBuild Phase"
  pre_build: 
    commands: 
      - "echo Pre_build Phase"
      - "npm install"
version: 0.2
